### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by FIRE-WATER799** [ShindouMihou/shieldbotlist#2]
I speak on behalf of ShieldBotList on saying that you need to change your policy. So no one can change the server count manually. I can not talk about why you need to do this as other people who do not like us may use it to thier advantage.

**Comment by FIRE-WATER799** [comment]
I am sorry it took me so long to recognize.

**Comment by ShindouMihou** [comment]
This repository is pretty deprecated as there are already several issues with it, the first being that the library isn't able to calculate multiple shards' server count and a few other details.

As of now, I don't have any plans at all to do any changes due to schedule reasons and for this issue, I don't see the part which you mean.

The library takes in the API entity of the library being used by the bot developer and grabs the server count by itself, there isn't any way to manipulate the server count manually.

For example on the Javacord side, this is how the code looks:
`api.getServers().size()`

Then again, even if people weren't able to set their server size by themselves. It doesn't mean the developers themselves cannot create their custom method which sends a falsified JSON call towards the endpoint containing falsified records.

**Comment by FIRE-WATER799** [comment]
If any one send a false server count they will be in trouble
